import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;
declare let clients: Clients;

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('push', (e) => {
    const data = e?.data?.json();

    self.registration.showNotification(data.title, {
        body: data.body,
    });
});

self.addEventListener('notificationclick', function(event) {
    event.notification.close();
    event.waitUntil(clients.openWindow('/'));
});
